### ISSUE TITLE
Define confirm and cancel reservations

### ISSUE THREAD

**Issue by dev-rafael-arevalo** [Ronmycode/FSJ24-A_Booking-API#7]
Define confirm and cancel reservations with followings considerations:
- Put a map service (Google, Leaflet, etc) with the address of host.
- Define nights reservations period in days
- Update With Cancel and Confirm states

Validations (If the start date has passed, not possible to cancel, if the end date has passed away, not possible to cancel and confirm).

**Comment by Ronmycode** [comment]
I couldn't make the API patch work to update the reservation status
